global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.CQRS;
global using Catalog.API.Models;
global using Marten;
global using FluentValidation;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.CustomException;