version: '3.4'

services:
  catalogdb:
    image: postgres   # Lấy image Postgres từ Docker Hub xuống

  basketdb:
    image: postgres   # Lấy image Postgres từ Docker Hub xuống

  distributedcache:   # Lấy image Redis từ Docker Hub xuống
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/DiscountGrpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:  

########################## CONTAINER #############################
# -catalog.api:
#  + catalogdb

# - basket.api:
#  + basketdb
#  + distributedcache (Redis)

# - Discount.api:
# + SqlLite
##################################################################
  
  
