version: '3.4'

services:
  catalogdb:
    image: postgres   # Lấy image Postgres từ Docker Hub xuống

  basketdb:
    image: postgres   # Lấy image Postgres từ Docker Hub xuống

  distributedcache:   # Lấy image Redis từ Docker Hub xuống
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
