version: '3.4'

services:
  catalogdb:                                          # Tên 'catalogdb' phải dc khai báo như trong docker-compose.yml
    container_name: Catalog_DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:  
      - postgres_catalog:/var/lib/postgresql/data/     #Tên 'postgres_catalog' phải dc khai báo như trong docker-compose.yml 

  basketdb:
    container_name: Basket_DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5433:5432"         # Chú ý để tránh xung đột thì port ko được đụng với catalogdb hoặc các port DB khác. 
                              # ConnectionString JSON cũng phải là port 5433
    volumes:
      - postgres_basket:/var/lib/postgresql/data/      #Tên 'postgres_basket' phải dc khai báo như trong docker-compose.yml 


  distributedcache:
    container_name: Distributed_cache
    restart: always
    ports:
      - "6379:6379"

  orderdb: # Tên này phải giống với tên trong docker-compose
   container_name: orderdb
   environment:           # Biến môi trường này rất quan trọng
    - ACCEPT_EULA=Y
    - SA_PASSWORD=SwN12345678
   restart: always
   ports:
    - "1433:1433" 

  messagebroker: # RABBITMQ (port default là 5672)
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 


################################################### -- DOCKER API -- ###########################################################################

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:    # Api run phụ thuộc vào catalogdb
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379  # distributedcache -> Tên ở line 30
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081   #discount.grpc -> Vùng chứa ở line 71
       
      # Tích hợp RabbitMQ vào BasketAPI (ghi đè các tham số trong json appsetting của BasketAPI)
      - MessageBroker__Host=amqp://ecommerce-mq:5672 # Thay thế localhost thành ecommerce-mq (line 47)
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest

    depends_on:   # Api run phụ thuộc vào BasketDb, distributedcache và discount.grpc
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker  # Nhớ depend thêm RabbitMQ
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
